### ISSUE TITLE
enhancing xcol argument in obs value function

### ISSUE THREAD

**Issue by ShanaScogin** [ShanaScogin/BayesPostEst#24]
@jkarreth  I added a potential solution to the xcol problem for you to look at - I added an argument takes the variable name, but I also left xcol as an argument. (A message spits out if both are supplied that it defaulted to the variable name argument.) I also added a second function that takes the formula, data, fit, and variable name instead of the model matrix, xrange, mcmcout, etc. I've called it mcmcSimObs. Do you want to take a look at those? If you like the extra variable name argument, I can add it to the average prob function.

**Comment by jkarreth** [comment]
very cool solution with xinterest in `mcmcObsProb.R`! I haven't tested this but if it checks out OK I think this is a great solution and I think we can go with it for mcmcAveProb as well.

I very much like the idea behind `mcmcSimObs` but am agnostic on whether we should include it now (vs. later). If it works, it would be terrific to keep it in the package. Otherwise, I think the more cumbersome model matrix, xrange etc. specification has pedagogical value, so it's fine with me to rely mainly on that.

@mlq38  @snpwill  if you have a chance to use `mcmcSimObs` with the Cowles data, let us know how it works!

**Comment by ShanaScogin** [comment]
Great! I've tested the xvariable argument on my simulated data and the examples on your website and it seems to be fine, but I'll test some more and add it to the average function. Also FYI - mcmcSimObs is actually slower than mcmcObsProb, which is to be expected (the median was 70 milliseconds slower over 100 runs with the simulated data [961 to 1030 millisecs] if I remember correctly), so that's worth noting. I saw it as not a replacement but more of an extra function if we want to include it. It could be something included with its own documentation, but that isn't spelled out in detail or only mentioned in passing in the main vignettes. I'm certainly not tied to it - I just wanted to cook it up for everyone's consideration!

**Comment by jkarreth** [comment]
I'll have to take a closer look but for now I think your suggestion is great - include it as an extra function with its own documentation. That said, I would prioritize it lower just during this week and get the package ready with the existing functions. 

Once the package is up, I'd love to see a more convenient solution like mcmcSimObs become part of the package. (Unless you can take care of it all at once 😃 - then let's absolutely include it.)

**Comment by ShanaScogin** [comment]
Going to close this one since the argument is added to both mcmcObsProb and mcmcAveProb and is passing testing so far. (More tests always welcome.) We can add a new one for the mcmcSimObs and mcmcSimAve if need be.
