### ISSUE TITLE
mcmcRocPrc is slow when full_sims = TRUE

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#25]
at some point, the underlying code needs to be optimized. lapply + loop = probably not good.

**Comment by ShanaScogin** [comment]
I'll prioritize everything else now, but I'd love to look into this eventually.

**Comment by jkarreth** [comment]
I think the issue is that we're using functions from the ROCR package which are apparently slow. Maybe we can one day replace the AUC calculations with our own function instead since we don't really need the overhead of ROCR for that.

**Comment by andybega** [comment]
I started taking a look at this. You're right, the ROCR functions are where most of the time is spent. From line profiling (second column is time, first is memory):

![Screen Shot 2019-09-02 at 14 33 30](https://user-images.githubusercontent.com/1353756/64112808-2074fa80-cd91-11e9-9f44-13d21930420a.png)

Here's a benchmark report with a v2 `mcmcRocPrc()` I started working on: https://github.com/andybega/BayesPostEst/blob/feature/rocprc-speed/tests/profile-mcmcRocPrc.md

For the ROC curves and AUC, `mlr` and `pROC` have some alternatives that can be checked:

- `measureAUC()` in https://github.com/mlr-org/mlr/blob/master/R/measures.R
- `colAUC()` in https://github.com/mlr-org/mlr/blob/master/R/Measure_colAUC.R
- `auc` in https://github.com/xrobin/pROC/blob/master/R/auc.R; this is also what yardstick uses
 
`yardstick` also has an option for PR curve and AUC, using their own solution:

- `pr_curve_binary()` in https://github.com/tidymodels/yardstick/blob/master/R/prob-pr_curve.R
- which is then fed into `auc` in https://github.com/tidymodels/yardstick/blob/master/R/prob-helpers.R

**Comment by andybega** [comment]
Slapping my own head, one easy way to shave off time when `curves = TRUE, fullsims = TRUE` is to use the existing curve data to compute AUCs, rather than redoing the whole thing. That should put that last block at a similar time to the third one (12s instead of 22s).

**Comment by andybega** [comment]
Ok, using the curves data indirectly is actually faster than directly using the `auc_roc` and `auc_pr` functions. 

This is with `curves = FALSE, fullsims = TRUE`; `f1()` is the current package version, `f2()` the new version:

```
## Unit: seconds
##  expr       min       lq     mean   median       uq      max neval cld
##  f1() 10.453441 11.21028 11.74057 11.55878 12.03372 14.28089    10   a
##  f2()  9.863609 10.91968 11.11132 11.01028 11.36222 12.75854    10   a
```

And now with `curves = TRUE, fullsims = TRUE`:

```
## Unit: seconds
##  expr       min        lq      mean    median       uq      max neval cld
##  f1() 21.238577 21.542162 22.141907 21.809533 23.07233 23.34445    10   b
##  f2()  9.393025  9.680966  9.873146  9.821037 10.14483 10.36802    10  a
```

That leaves:

- switch the calculation when `curves = FALSE` to use curves for the median `pred_probs` + manual AUC calculation, since that seems to be faster anyways
- find a more efficient way to generate the curve data

**Comment by andybega** [comment]
Alright, doing a re-implementation of the ROC and PR curve calculations did the trick. This is with `fullsims = TRUE`, `f1()` is current version `f2()` is the new replacement.

With `curves = FALSE`:
```
## Unit: seconds
##  expr       min        lq     mean    median        uq      max neval cld
##  f1() 11.280333 11.350524 11.50423 11.543556 11.629966 11.72832    10   b
##  f2()  1.501663  1.687164  1.69418  1.705164  1.728044  1.77488    10  a
```

With `curves = TRUE`:
```
## Unit: seconds
##  expr       min        lq      mean    median        uq       max neval
##  f1() 22.428992 26.025205 27.193896 27.083906 27.977556 33.280823    10
##  f2()  1.597306  1.734178  1.903603  1.822698  1.971806  2.548052    10
##  cld
##    b
##   a
```

About 2 seconds to run it for the `jags_logit` example. There is a note at https://github.com/andybega/BayesPostEst/blob/f1da23b9db86461d4f9c671d9393265dd10578c5/tests/profile-mcmcRocPrc.md that documents that the results are equivalent, and which shows the speed comparison benchmarks. 

I'm going to remove that note and otherwise clean up stuff so that this can be merged in.

**Comment by jkarreth** [comment]
Fantastic! Thank you!

**Comment by jkarreth** [comment]
@ShanaScogin , since this is merged in, we can close this issue, right?

**Comment by ShanaScogin** [comment]
Was this merged? (@andybega?) If it has, then ya, let's close it. I think I just missed when it was included.

**Comment by andybega** [comment]
Not yet, I'm about to merge in your recent changes from `develop` to make sure nothing breaks and will then do a pull request.

**Comment by ShanaScogin** [comment]
Tests all look great. You're the best. Closing this.

**Comment by andybega** [comment]
Yay! Thanks
