### ISSUE TITLE
Caution: mcmc output conversion from JAGS/BUGS: order of columns

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#29]
For mcmcAveProb etc.: 

If we define generate `mcmcout` as something like `mcmc.mat[, 1:ncol(xmat)` (where mcmc.mat is the mcmc object transformed into a matrix, and xmat is the model matrix)

then we need to make sure that the mcmc object indeed has coefficients listed first. For Stan objects, this is usually the case. But JAGS objects may list coefficients alphabetically. So just pulling the first $k$ columns of the mcmc matrix may not keep the desired columns.

**Comment by ShanaScogin** [comment]
Re: adding the code that converts the post. distribs. into matrices from mcmcTab into mcmcAveProb, mcmcObsProb, and mcmcFD - after messing with them with a number of models and seeing what you were saying about how much jags can shift up the variables, I'm nervous about automating that part until we find a way to match up the column names. Perhaps that's why you had left them out initially? What do you think? I added to the documentation to the argument if you want to check. 

On this point, I might make a branch to house the more automated sims functions I have going on there to shelf for if/when we can think of a solution to the sorting.

**Comment by ShanaScogin** [comment]
re: this issue on the rocprc - is it better that we also add these types of arguments to that one instead of what is there? The only thing I worry about generalizing the 'sims' argument to something more than stan is that model.frame(xyz) doesn't act the same on all of those class objects (unless you know of a way to make it so it does).

**Comment by jkarreth** [comment]
You're right on all of the above. And yes, I think that was my reason for keeping the extra step to create mcmc objects by hand. So...

1. let's not automate the conversion of model objects to coefficient matrices just now
2. let's rely on the warning in the documentation to prevent false column ordering
3. I like the idea of new branch for automated sim functions - we can figure that out later
4. good idea about mcmcRocPrc. How about the following:

- [x] user specifies mcmcout as in mcmcAveProb (with warning in documentation about column order)
- [x] user specifies model frame as user does for model matrix in mcmcAveProb, i.e. `modelframe = model.frame(y ~ x1 + x2 + ..., data = d)`
- [x] `pred_prob` will become `<- plogis(t(modelframe %*% t(mcmcout)))` (or more explicitly in two steps, first `Xb <- t(modelframe %*% t(mcmcout))` and then `pred_prob <- exp(Xb) / (1 + exp(Xb))`

**Comment by ShanaScogin** [comment]
I used the model matrix for the pred probs and the plogis() route in a separate test function. Does this sound right? 

https://github.com/ShanaScogin/BayesPostEst/blob/master/R/mcmcRocPrctest.R

**Comment by jkarreth** [comment]
I think that looks right! We should just add an option for the probit as well - had forgotten about that before. Let's do this akin to what we did in mcmcAveProb and mcmcObsProb:

```
if(link == "logit"){
pred_prob <- plogis(t(modelmatrix %*% t(mcmcout)))
}

if(link == "probit"){
pred_prob <- pnorm(t(modelmatrix %*% t(mcmcout)))
}
```

and then add `link = "logit"` to the function call.

**Comment by ShanaScogin** [comment]
This is done - feel free to close this issue unless you have something else

**Comment by jkarreth** [comment]
looks good!
