### ISSUE TITLE
mcmcReg: make "pars" an optional argument

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#40]
@jayrobwilliams - so that `mcmcReg` prints all parameters by default (if you agree that's desirable).

**Comment by jayrobwilliams** [comment]
My thought on this is that Bayesian models tend to have a lot of nuisance/hierarchical parameters, and printing all by default might not be that useful for most models people are actually estimating. Since we have to work with all samples to calculate credible intervals, I worry that defaulting to all parameters could also create performance issues. Do you think the benefits outweigh these potential drawbacks?

**Comment by jkarreth** [comment]
That's a good point and I could get behind that. 

Then again, I like the texreg default behavior of printing all parameters but allowing for `omit.coef`. Could we do the same and...

- [x] include a `pars` option but leave it optional
- [x] add a mention in the help file that with a large number of parameters, users should specify `pars` explicitly
- [ ] add a conditional warning, say if the number of pars > 20, the warning prints "With a large number of parameters (> 20), mcmcReg will be slow. You can select parameters using "pars". Would you like to continue printing all parameters? y/n"

Maybe the third option is too unwieldy, but what do you think about the first and second?

**Comment by jayrobwilliams** [comment]
added in a82be312c92360b2fd7b2423901df1fd9221e957
