### ISSUE TITLE
add Pr argument to mcmcReg, analogous to mcmcTab

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#75]
A nice-to-have: add the `Pr` (percent of posterior draws with same sign as median) argument to mcmcReg, so that it can be printed under the median of the posterior (like the SD or HDPI).

The easystats package has this implemented in some way:
<https://easystats.github.io/bayestestR/reference/p_direction.html>

Similarly, we could also add the percent outside the ROPE, like easystats does ([here](https://easystats.github.io/bayestestR/reference/rope.html))

Not to get too carried away :) but I think this could still be worthwhile because the easystats/parameters functions don't lead to a classical regression table (yet).

**Comment by jayrobwilliams** [comment]
Turns out I did this (mostly) back in db88052c48ff17503589292dab5436717e622dcc and I just made it so the the code automatically uses the correct point estimate (mean or median) in the calculation in fe2cb41f957fdef8c0773285c002a16b87e67ee3. Once we get this current release approved on CRAN I'll merge fe2cb41f957fdef8c0773285c002a16b87e67ee3 into develop.

**Comment by jkarreth** [comment]
Fantastic! Thank you @jayrobwilliams  for doing this.
