### ISSUE TITLE
Standardize function names

### ISSUE THREAD

**Issue by jkarreth** [ShanaScogin/BayesPostEst#8]
use lowerCamelCase, e.g. mcmcTab

**Comment by ShanaScogin** [comment]
I added some draft names. A couple things to note - 1.) I changed the function that does the sim pred prob for logit to 'mcmcPredProb' (since setting the other values to the mean/med is the standard as far as I know) and left the obs prob as 'mcmcObsProb.' There might be a better option than this. 2.) I also changed the probit plotting function to 'mcmcProbitPlot' (instead of mcmcProbitPlotPP) since we might want to add PP and FD functionality. FD might want to be its own function though.

**Comment by jkarreth** [comment]
Sounds good; my suggestions:

- [x] let's use mcmcAvgProb and mcmcObsProb; the former is consistent with the language in Hanmer & Kalkan (2013)

- [ ] since mcmcProbitPlot simply plots the probabilities that are generated by mcmcAvgProb, we should remove the first part (generating the probabilities) and just make it a plotting function, something like mcmcPPplot

- [ ] ... and analogously, we can create a separate mcmcFDplot (I'll think more about what this will be)

- [ ] In the short run, highest priority to fix mcmcAvgProb and mcmcObsProb; the plotting functions can come later. We could also leave the plotting to the users (for now).

**Comment by jkarreth** [comment]
Renaming is now complete and edits to functions are all documented in separate issues.
